package kaviney;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import java.util.Optional;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import kaviney.Uzsakymai;
import kaviney.UzsakymaiRepository;

import kaviney.Patiekalai;
import kaviney.PatiekalaiRepository;

import kaviney.TopPatiekalai;
import kaviney.TopPatiekalaiAtaskaita;

import kavinex.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/restfull") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UzsakymaiRepository uzsakymaiRepository;
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data	
	private PatiekalaiRepository patiekalaiRepository;
	
	
	// cia pridedu produktus
	@Autowired private ProduktaiRepository produktaiRepository;
	
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String naujasProduktas (@RequestParam String pav
			, @RequestParam String mat_vnt 
			, @RequestParam Integer mat_kiek
			, @RequestParam Double kaina
			, @RequestParam Double kiekis_sand			
			) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		Produktai n = new Produktai();
		n.setPav(pav);
		n.setMat_vnt(mat_vnt);
		n.setMat_kiek(mat_kiek);
		n.setKaina(kaina);
		n.setKiekis_sand(kiekis_sand);
		System.out.println (n.toString() );
		produktaiRepository.save(n);
		return "Saved";
	}
	
	//cia bandau prideti šalinimą....
	
	
	@GetMapping(path="/del-product") // Map ONLY GET Requests
	public @ResponseBody String keistiIrasa ( @RequestParam Integer id ) {
	
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		Optional <Produktai> found = produktaiRepository.findById( id );
		
		// variantas trynimui
		//produktaiRepository.deleteById(id);
		
		String res = "Not done";
		
		if ( found.isPresent() ) {
			
			   Produktai n = found.get();
			   n.setId(id);
			   //java.util.Date dt = new java.util.Date();
			   //java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			   //String currentTime = sdf.format(dt);			   
			   produktaiRepository.save(n);	
			   res = "Saved";
			}		
		return res;
	}	
	
	 @GetMapping(path="/lst-produktai")
		public @ResponseBody Iterable<Produktai> getAllProduktai() {
		// This returns a JSON or XML with the users
		 return produktaiRepository.findAll();
	}
	
	 
	 
	// @GetMapping(path="/del-product")
		//public @ResponseBody Iterable<Produktai> getAllProduktaix() {
		// This returns a JSON or XML with the users
		 //return produktaiRepository.findAll();
	//}
	
	@GetMapping(path="/patiekalas")
	public @ResponseBody Optional<Patiekalai> getPatiekalas(@RequestParam Integer id) {
		// This returns a JSON or XML with the users
		Optional <Patiekalai> found = patiekalaiRepository.findById( id );		
		/*
		if ( found.isPresent() ) {
			
			   Uzsakymai n = found.get();
			}	
		*/	
		return found;
	}	
	
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Uzsakymai> getAllUzsakymai() {
		// This returns a JSON or XML with the users
		return uzsakymaiRepository.findAll();
	}
	

	
	 
	 @GetMapping(path="/allx")
	public @ResponseBody Iterable<Patiekalas> getAllUzsakymaix() {
		// This returns a JSON or XML with the users
		ApplicationContext context = new ClassPathXmlApplicationContext( "file:src/beans.xml" );
		
		UzsakymaiSpring uzsakymai = (UzsakymaiSpring) context.getBean( "uzsakymai" );
		uzsakymai.nuskaityti(); // tik ivedimas
		uzsakymai.ruostiPatiekalus();
		uzsakymai.patiekti();
		;		
		
		return uzsakymai.isnesiotix();
	}
	
	
	@GetMapping(path="/top-patiekalai")
	public @ResponseBody Iterable<TopPatiekalai> getTopPatiekalai(
			@RequestParam String laikotarpis_nuo
			, @RequestParam String laikotarpis_iki
	) {
		
//		 Map<String, String> properties = new HashMap<String, String>();
//		  properties.put("javax.persistence.jdbc.user", "root");
//		  properties.put("javax.persistence.jdbc.password", "");
//		  EntityManagerFactory emf = Persistence.createEntityManagerFactory("TopPatiekalaiAtaskaita");   // Persistence.createEntityManagerFactory( "jdbc:mysql://localhost:3306/spring_jpa/kavine;user=root;password=");		
		
	    EntityManagerFactory emf = Persistence.createEntityManagerFactory( "TopPatiekalaiAtaskaita" ); // "Eclipselink_JPA" );
		EntityManager entitymanager = emf.createEntityManager();
				
		TopPatiekalaiAtaskaita tp = new TopPatiekalaiAtaskaita( entitymanager );

		return tp.topPatiekalai(laikotarpis_nuo, laikotarpis_iki);
	}	

}
